name: Swift

on:
  push:
    tags: ["*"]
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test-substate-macos-10-15:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: set -o pipefail; xcodebuild test -scheme Substate -destination 'platform=macOS' | xcpretty
  test-counter-ios-15-0:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: set -o pipefail; xcodebuild test -scheme 'Counter (iOS)' -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 12 mini' | xcpretty
