name: Swift

on:
  push:
    tags: [none]
    branches: [none]
  pull_request:
    branches: [none]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Swift
        uses: fwal/setup-swift@v1
      - name: Print Swift Version
        run: swift --version
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v
