name: Swift

on:
  push:
    tags: ["*"]
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Swift
        uses: fwal/setup-swift@v1
      - name: Build
        run: swift build
      - name: Test
        run: swift test
