name: Swift

on:
  push:
    tags: ["*"]
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:

  "Test Substate (macOS)":
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: set -o pipefail; xcodebuild test -scheme Substate -destination 'platform=macOS' | xcpretty

  "Test Substate (iOS)":
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: set -o pipefail; xcodebuild test -scheme Substate -destination 'platform=iOS Simulator,OS=14.4' | xcpretty

  "Test Substate Middleware (macOS)":
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: set -o pipefail; xcodebuild test -scheme SubstateMiddleware -destination 'platform=macOS' | xcpretty


  # TODO: Enabled once Github supports iOS 15
  # test-counter-ios-15-0:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Test
  #       run: set -o pipefail; xcodebuild test -scheme 'Counter (iOS)' -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 12 mini' | xcpretty
